name: flutter_html
description: A Flutter widget rendering static HTML and CSS as Flutter widgets.
publish_to: 'none'
version: 2.2.1+1
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  # Plugin for parsing html
  html: '>=0.15.0 <1.0.0'

  # Plugins for parsing css
  csslib: '>=0.17.0 <1.0.0'

  # Plugins for rendering the <table> tag.
  flutter_layout_grid: '>=2.0.0 <3.0.0'

  # Plugins for rendering the <video> tag.
  # disabled to avoid future conflicts
  # video_player: '>=2.1.1 <3.0.0'
  # chewie: '>=1.1.0 <2.0.0'

  # Plugin for rendering the <iframe> tag.
  # disabled due to conflict with current major: 4.x.x 
  # webview_flutter: '>=2.0.4 <3.0.0'

  # Plugins for rendering the <audio> tag.
  # disabled to avoid future conflicts
  # chewie_audio: '>=1.2.0 <2.0.0'

  # Plugins for rendering the <svg> tag.
  flutter_svg: '>=2.0.0 <3.0.0'

  # Plugin for rendering MathML
  # disabled due to conflict with flutter_svg 2.x.x
  # and requirement sdk >=3.0.0 from version 0.7.1
  # flutter_math_fork: '>=0.4.2+1 <1.0.0'

  # plugin for firstWhereOrNull extension on lists
  collection: '>=1.15.0 <2.0.0'

  # plugin to convert integers to numerals
  numerus: '>=1.1.1 <2.0.0'

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
